config:
      app:
          name: ms-config
      server:
            port: 8888
            git:
                uri:
                    local: ${HOME}/Git Projects/serasa-config-repo
                    remote: https://github.com/DavidGuimaraes/serasa-config-repo
            uri: http://localhost:${config.server.port}

spring.application.name: ${config.app.name}
server.port: ${config.server.port}
spring.cloud.config.server.git.uri: ${config.server.git.uri.remote}