request:
  order:
    server:
      port: 8083

server.port: ${request.order.server.port}

spring:
  rabbitmq:
    username: rabbit666
    password: melhorsenhadomundo
    # host: rabbitmq
    host: localhost
  cloud:
    stream:
      bindings:
        input:
          destination: compra
          group: buyprocess

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      # defaultZone: http://ms-discovery:8761/eureka

fila.entrada: queue-order-waiting
fila.finalizado: queue-order-done