order:
  server:
    port: 8084

server.port: ${order.server.port}

spring:
  data:
    mongodb:
      # host: mongo
      host: localhost
      port: 27017
      database: order
      repositories:
        enabled: true
    rabbitmq:
      username: rabbit666
      password: melhorsenhadomundo
      # host: rabbitmq
      host: localhost
  redis:
    host: localhost
    # host: redis
    port: 6379
  cloud:
    stream:
      bindings:
        input:
          destination: compra
          group: buyprocess
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      # defaultZone: http://ms-discovery:8761/eureka

fila.entrada: queue-order-waiting
fila.finalizado: queue-order-done