order:
  server:
    port: 8084

server.port: ${order.server.port}

spring:
  data:
    mongodb:
      # host: mongo
      host: localhost
      port: 27017
      database: order
      repositories:
        enabled: true

fila.entrada: queue-order-waiting
fila.finalizado: queue-order-done