order:
  server:
    port: 8084

server.port: ${order.server.port}

spring:
  data:
    mongodb:
      # host: mongo
      host: localhost
      port: 27017
      database: order
      repositories:
        enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  rabbitmq:
    username: rabbit666
    password: melhorsenhadomundo
    # host: rabbitmq
    host: localhost
  cloud:
    stream:
      bindings:
        input:
          destination: compra
          group: buyprocess

fila.entrada: queue-order-waiting
fila.finalizado: queue-order-done