user:
  server:
    port: 8082

server.port: ${user.server.port}

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/user
    # url: jdbc:postgresql://postgres:5432/user
    username: postgres
    password: 123456
  main:
    allow-bean-definition-overriding: true
  jackson.deserialization.fail-on-unknown-properties: true